#!/usr/bin/env bash



create_tls_secrets() {

    CERTS_PATH=${OPENSTACK_KUBE_SECRETS_PATH}/clusters/${CLUSTER}/certs


    for f in $CERTS_PATH/*
    do
        file=${f##*/}
        COMMON_NAME=${file%.key}

        if [ "$file" == "$COMMON_NAME.key" ]
        then

            if [ -f "$CERTS_PATH/${COMMON_NAME}.pem" ]
            then
                SECRET_NAME=$(echo $COMMON_NAME | tr . -)

                kubectl get secret | grep tls-$SECRET_NAME >/dev/null 2>&1

                    if [ $? -eq 0 ]
                    then
                        echo "TLS secret tls-$SECRET_NAME already exists"
                    else
                        kubectl create secret generic tls-$SECRET_NAME --namespace=$NAMESPACE --from-file=tls.crt=$CERTS_PATH/$COMMON_NAME.pem --from-file=tls.key=$CERTS_PATH/$COMMON_NAME.key
                    fi
            fi
        fi



    done

}