#!/usr/bin/env python

import sys,os



module_path = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)),'../../kube'))
if module_path not in sys.path:
    sys.path.append(module_path)

from deployment import Deployment






try:
    cluster = sys.argv[1]
except IndexError:
    cluster=None
if not cluster:
    print("Usage : prepare_deployment [cluster]")
    sys.exit(1)

kube_root = os.path.realpath(os.path.join(os.path.dirname(os.path.realpath(__file__)),"../../"))

deployment = Deployment(kube_root=kube_root,cluster=cluster)
deployment.execute()














