#!/usr/bin/env python
import os
import sys
from jinja2 import Environment, FileSystemLoader

path,template = os.path.split(sys.argv[1])

env = Environment(loader=FileSystemLoader(path))
template = env.get_template(template)
print template.render(os.environ)