@secret_vars = %w{
	MONSOON_DB_PASSWORD
	SECRET_KEY_BASE
	MONSOON_OPENSTACK_AUTH_API_PASSWORD
	MONSOON_SWIFT_PASSWORD
	MONSOON_SWIFT_TEMP_URL_KEY
	SENTRY_DSN
}

@config_vars = %w{
	RAILS_ENV
	MONSOON_OPENSTACK_AUTH_API_ENDPOINT
	MONSOON_OPENSTACK_AUTH_API_USERID
	MONSOON_OPENSTACK_AUTH_API_DOMAIN
	MONSOON_SWIFT_USERNAME
	MONSOON_SWIFT_USER_DOMAIN_ID
	MONSOON_SWIFT_PROJECT_NAME
	MONSOON_SWIFT_PROJECT_DOMAIN_NAME
}

@config_map_name = File.basename File.expand_path('../', __FILE__)
@secret_name = File.basename File.expand_path('../', __FILE__)
	
