@secret_vars = %w{
	MONSOON_DB_PASSWORD
	MONSOON_OPENSTACK_AUTH_API_PASSWORD
	MONSOON_RAILS_SECRET_TOKEN
	SENTRY_DSN
}

@config_vars = %w{
	RAILS_ENV
  MONSOON_DASHBOARD_REGION
	MONSOON_DASHBOARD_LANDSCAPE
	MONSOON_OPENSTACK_AUTH_API_ENDPOINT
	MONSOON_OPENSTACK_AUTH_API_USERID
	MONSOON_OPENSTACK_AUTH_API_DOMAIN
	SWIFT_RESELLERADMIN_ROLE
	SWIFT_RESELLERADMIN_PROJECT
	SWIFT_RESELLERADMIN_PROJECT_DOMAIN
	SWIFT_RESELLERADMIN_REGION
  ARC_UPDATES_URL
  ARC_PKI_URL
  ARC_BROKER_URL
}

@config_map_name = File.basename File.expand_path('../', __FILE__)
@secret_name = File.basename File.expand_path('../', __FILE__)
