#!/usr/bin/env bash
set -x

CLUSTER_SCRIPT_PATH=${0%/*}
. $CLUSTER_SCRIPT_PATH/common

function bootstrap {
   #Not especially proud of this, but it works (unlike the environment variable approach in the docs)
   chown -R rabbitmq:rabbitmq /var/lib/rabbitmq

   /etc/init.d/rabbitmq-server start

   rabbitmq-plugins enable rabbitmq_tracing
   rabbitmqctl trace_on

   rabbitmqctl add_user $RABBITMQ_DEFAULT_USER $RABBITMQ_DEFAULT_PASS || true
   rabbitmqctl set_permissions $RABBITMQ_DEFAULT_USER ".*" ".*" ".*" || true

   rabbitmqctl add_user $RABBITMQ_ADMIN_USER $RABBITMQ_ADMIN_PASS || true
   rabbitmqctl set_permissions $RABBITMQ_ADMIN_USER ".*" ".*" ".*" || true
   rabbitmqctl set_user_tags $RABBITMQ_ADMIN_USER administrator || true

   rabbitmqctl add_user $RABBITMQ_METRICS_USER $RABBITMQ_METRICS_PASS || true
   rabbitmqctl set_permissions $RABBITMQ_METRICS_USER ".*" ".*" ".*" || true
   rabbitmqctl set_user_tags $RABBITMQ_METRICS_USER monitoring || true

   rabbitmqctl change_password guest $RABBITMQ_DEFAULT_PASS || true
   rabbitmqctl set_user_tags guest monitoring || true
   /etc/init.d/rabbitmq-server stop
}


function start_application {
   exec rabbitmq-server
}

bootstrap
start_application


